"""Spawn-manifest writer：讓 /pr-cycle-fast skill 知道要 dispatch 哪些 subagent。"""

from __future__ import annotations

from pathlib import Path

from .._paths import RUNTIME_DIR
from .config import _safe_repo
from .models import OrchestratorState

_MANIFEST_BASE = RUNTIME_DIR / "pr_orchestrator"


def manifest_path(repo: str, pr_number: int) -> Path:
    return _MANIFEST_BASE / _safe_repo(repo) / str(pr_number) / "spawn-manifest.md"


def write_review_manifest(state: OrchestratorState) -> Path:
    """為 REVIEWING 狀態寫出 spawn-manifest.md。

    /pr-cycle-fast skill 讀取此檔後在同一個 message 內 dispatch 三個並行 subagent。
    """
    pr = state.pr_number
    branch = state.branch
    base = state.base_branch

    content = f"""\
# Subagent Spawn Manifest — PR #{pr}

<!-- auto-generated by tasks.pr_orchestrator.dispatcher; do not edit -->

## Context
- Branch: `{branch}`
- Base: `{base}`
- State: `{state.current_state}`

## Parallel Tasks (launch all three in a SINGLE message)

### 1. code-review
subagent_type: pr-review-toolkit:code-reviewer
prompt: |
  Review PR #{pr} (branch `{branch}` → `{base}`).
  Focus on: logic errors, silent failures, test coverage gaps, security issues.
  Run `gh pr diff {pr}` to get the diff.
  Write findings to a structured review summary.

### 2. ci-monitor
subagent_type: general-purpose
prompt: |
  Monitor CI for PR #{pr}.
  Run: `gh pr checks {pr} --watch`
  When ALL checks pass, write the word "CI_PASS" to stdout and exit.
  When any check fails, write "CI_FAIL:<job_name>" and exit.
  Timeout: 20 minutes.

### 3. conflict-detector
subagent_type: general-purpose
prompt: |
  Check merge conflict status for PR #{pr}.
  Run: `gh pr view {pr} --json mergeable,mergeStateStatus`
  If mergeable == "CONFLICTING", write "CONFLICT" to stdout and exit.
  Otherwise write "OK" and exit.

## Instructions for /pr-cycle-fast skill
1. Launch all three subagents above in the SAME message (parallel dispatch).
2. Collect all three results before advancing the state machine.
3. On code review + CI + conflict check all complete, run in order:
   ```bash
   uv run python -m tasks.pr_orchestrator transition --pr {pr} --to REVIEW_DONE \
       --reason "review subagents completed" --repo-root "$REPO_ROOT"
   uv run python -m tasks.pr_orchestrator transition --pr {pr} --to CI_WAIT \
       --reason "awaiting CI" --repo-root "$REPO_ROOT"
   ```
"""
    p = manifest_path(state.repo, pr)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p
