"""Daily digest 生成器。"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from tasks._paths import PROJECT_ROOT, RUNTIME_DIR

from .models import FrictionCluster, NightlyDigest, PRRecord


class DigestWriter:
    """產生 Markdown digest 並寫入 .runtime/nightly-agent/digests/。"""

    def __init__(self, digest_dir: str | Path | None = None) -> None:
        self.digest_dir = (
            Path(digest_dir) if digest_dir else RUNTIME_DIR / "nightly-agent" / "digests"
        )

    def build(
        self,
        date: str,
        lookback_hours: int,
        all_events_count: int,
        all_clusters: list[FrictionCluster],
        prs: list[PRRecord],
        skipped: int,
        errors: list[str],
    ) -> NightlyDigest:
        eligible = [c for c in all_clusters if c.count >= 2]
        digest_text = self._render(
            date, lookback_hours, all_events_count, all_clusters, eligible, prs, skipped, errors
        )
        return NightlyDigest(
            date=date,
            lookback_hours=lookback_hours,
            friction_events_found=all_events_count,
            clusters_found=len(all_clusters),
            clusters_eligible=len(eligible),
            artifacts_drafted=len(prs) + skipped,
            tests_validated=len(prs),
            prs_opened=len(prs),
            skipped_no_test=skipped,
            prs=prs,
            errors=errors,
            digest_text=digest_text,
        )

    def write(self, digest: NightlyDigest) -> Path:
        self.digest_dir.mkdir(parents=True, exist_ok=True)
        filename = f"digest-{digest.date}.md"
        output_path = self.digest_dir / filename
        output_path.write_text(digest.digest_text, encoding="utf-8")
        return output_path

    def _render(
        self,
        date: str,
        lookback_hours: int,
        events_count: int,
        all_clusters: list[FrictionCluster],
        eligible: list[FrictionCluster],
        prs: list[PRRecord],
        skipped: int,
        errors: list[str],
    ) -> str:
        lines: list[str] = [
            f"# Nightly Self-Improvement Digest — {date}",
            "",
            f"**Lookback:** last {lookback_hours}h  ",
            f"**Friction events found:** {events_count}  ",
            f"**Clusters found:** {len(all_clusters)}  ",
            f"**Clusters eligible (≥2):** {len(eligible)}  ",
            f"**PRs opened:** {len(prs)}  ",
            f"**Skipped (test failed):** {skipped}  ",
            "",
        ]

        if prs:
            lines += ["## PRs Opened", ""]
            for pr in prs:
                lines.append(f"- [{pr.pr_number}]({pr.pr_url}) — `{pr.artifact_file}`")
            lines.append("")

        if eligible:
            lines += ["## Eligible Clusters", ""]
            for cluster in eligible:
                status = (
                    "✅ PR opened"
                    if any(p.proposal_id.startswith(cluster.id[:8]) for p in prs)
                    else "⏭ skipped"
                )
                lines.append(
                    f"- **{cluster.friction_type}** (×{cluster.count}) — "
                    f"kws: `{', '.join(cluster.common_keywords[:5])}` — {status}"
                )
            lines.append("")

        if errors:
            lines += ["## Errors", ""]
            for e in errors[:10]:
                lines.append(f"- {e}")
            lines.append("")

        lines += [
            "---",
            f"*Generated by `tasks.nightly_agent` at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        ]

        return "\n".join(lines) + "\n"
