"""Test Validator：生成 failing→passing test，確保 artifact 真的能防止 friction。"""

from __future__ import annotations

import re
import subprocess  # nosec B404
import textwrap
from pathlib import Path

from tasks._paths import PROJECT_ROOT

from .models import ArtifactProposal, ArtifactType, TestResult


def _get_main_repo() -> Path:
    """Return main repo root (handles worktree: uses --git-common-dir)."""
    result = subprocess.run(  # nosec B603 B607
        ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode == 0:
        return Path(result.stdout.strip()).parent
    return PROJECT_ROOT


# ---------------------------------------------------------------------------
# Test template generators per artifact type
# ---------------------------------------------------------------------------


def _test_for_hookify_rule(proposal: ArtifactProposal) -> str:
    """Generate pytest for a new Python PreToolUse hook.

    Failing condition (before): hook file does not exist, so the check never runs.
    Passing condition (after): hook file exists and blocks the problematic pattern.
    """
    hook_path = proposal.target_file
    bad_cmd = _extract_bad_command(proposal)
    # Use repr() to get a properly-escaped Python string literal (handles \n, quotes, etc.)
    bad_cmd_repr = repr(bad_cmd)

    return textwrap.dedent(f'''\
        """
        NIGHTLY-{proposal.id[:8]} — generated by nightly-agent
        Validates: {proposal.title}
        Artifact: {hook_path}

        Failing test: hook file does not exist → friction undetected.
        Passing test: hook file exists and blocks the pattern.
        """
        import json
        import subprocess
        from pathlib import Path

        import pytest

        # Resolve repo root at test execution time (not generation time)
        _root = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"], text=True
            ).strip()
        )
        HOOK_PATH = _root / "{hook_path}"
        BAD_CMD = {bad_cmd_repr}


        def test_hook_file_exists():
            """Rule file must be present before this test can pass."""
            assert HOOK_PATH.exists(), (
                f"Hook not found: {{HOOK_PATH}}\\n"
                "The nightly-agent PR must create this file."
            )


        def test_hook_blocks_bad_command():
            """Hook must exit non-zero for the problematic command."""
            assert HOOK_PATH.exists(), "skip — hook not yet created"
            hook_input = {{
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
                "tool_input": {{"command": BAD_CMD}},
            }}
            result = subprocess.run(  # nosec B603
                ["python3", str(HOOK_PATH)],
                input=json.dumps(hook_input),
                text=True,
                capture_output=True,
                timeout=10,
            )
            assert result.returncode != 0, (
                f"Hook should have blocked:\\n  {{BAD_CMD}}\\n"
                f"stdout: {{result.stdout[:200]}}\\nstderr: {{result.stderr[:200]}}"
            )


        def test_hook_allows_good_command():
            """Hook must exit 0 for a clean command."""
            if not HOOK_PATH.exists():
                pytest.skip("hook not yet created")
            good_input = {{
                "hook_event_name": "PreToolUse",
                "tool_name": "Bash",
                "tool_input": {{"command": 'echo "clean command"'}},
            }}
            result = subprocess.run(  # nosec B603
                ["python3", str(HOOK_PATH)],
                input=json.dumps(good_input),
                text=True,
                capture_output=True,
                timeout=10,
            )
            assert result.returncode == 0, (
                f"Hook should have allowed clean command\\n"
                f"stderr: {{result.stderr[:200]}}"
            )
    ''')


def _test_for_claude_md_gotcha(proposal: ArtifactProposal) -> str:
    """Generate pytest for a CLAUDE.md gotcha addition.

    Failing condition (before): the gotcha text is not in CLAUDE.md.
    Passing condition (after): PR has added the text.
    """
    phrase = _extract_distinctive_phrase(proposal.content)
    phrase_repr = repr(phrase)
    target = proposal.target_file

    return textwrap.dedent(f'''\
        """
        NIGHTLY-{proposal.id[:8]} — generated by nightly-agent
        Validates: {proposal.title}
        Artifact: {target}

        Failing test: gotcha text not yet present in target file.
        Passing test: PR has added it.
        """
        import subprocess
        from pathlib import Path

        _root = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"], text=True
            ).strip()
        )
        TARGET_FILE = _root / "{target}"
        DISTINCTIVE_PHRASE = {phrase_repr}


        def test_gotcha_present_in_target():
            """Gotcha must appear in the target file after the PR lands."""
            assert TARGET_FILE.exists(), f"Target file not found: {{TARGET_FILE}}"
            content = TARGET_FILE.read_text(encoding="utf-8")
            assert DISTINCTIVE_PHRASE.lower() in content.lower(), (
                f"Gotcha not found in {{TARGET_FILE}}\\n"
                f"Expected phrase: {{DISTINCTIVE_PHRASE!r}}\\n"
                "The nightly-agent PR must add this gotcha."
            )
    ''')


def _test_for_skill_update(proposal: ArtifactProposal) -> str:
    """Generate pytest for a SKILL.md section addition."""
    phrase = _extract_distinctive_phrase(proposal.content)
    phrase_repr = repr(phrase)
    target = proposal.target_file

    return textwrap.dedent(f'''\
        """
        NIGHTLY-{proposal.id[:8]} — generated by nightly-agent
        Validates: {proposal.title}
        Artifact: {target}
        """
        import subprocess
        from pathlib import Path

        _root = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"], text=True
            ).strip()
        )
        TARGET_FILE = _root / "{target}"
        DISTINCTIVE_PHRASE = {phrase_repr}


        def test_skill_section_present():
            """New section must appear in the skill after the PR lands."""
            assert TARGET_FILE.exists(), f"Skill file not found: {{TARGET_FILE}}"
            content = TARGET_FILE.read_text(encoding="utf-8")
            assert DISTINCTIVE_PHRASE.lower() in content.lower(), (
                f"Section not found in {{TARGET_FILE}}\\n"
                f"Expected: {{DISTINCTIVE_PHRASE!r}}"
            )
    ''')


_TEST_GENERATORS = {
    ArtifactType.HOOKIFY_RULE: _test_for_hookify_rule,
    ArtifactType.CLAUDE_MD_GOTCHA: _test_for_claude_md_gotcha,
    ArtifactType.SKILL_UPDATE: _test_for_skill_update,
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _extract_bad_command(proposal: ArtifactProposal) -> str:
    """Try to find a real bad command from friction descriptions."""
    for desc in proposal.friction_descriptions:
        m = re.search(r"`([^`]{5,80})`", desc)
        if m:
            return m.group(1)
    if "em_dash" in proposal.target_file or "ap2" in proposal.target_file:
        return 'echo "test — em dash"'
    if "worktree" in proposal.target_file:
        return "git checkout main"
    return 'echo "example bad command"'


def _extract_distinctive_phrase(content: str) -> str:
    """Extract the most distinctive short phrase from artifact content for test assertion."""
    m = re.search(r"\*\*([^*]{5,60})\*\*", content)
    if m:
        return m.group(1)
    m = re.search(r"##\s+(.{5,60})", content)
    if m:
        return m.group(1).strip()
    for line in content.splitlines():
        line = line.strip().lstrip("-# *")
        if len(line) > 10:
            return line[:60]
    return content[:40]


# ---------------------------------------------------------------------------
# TestValidator
# ---------------------------------------------------------------------------


class TestValidator:
    """生成 test file 並驗證 failing-then-passing 語意。"""

    def __init__(self, generated_tests_dir: str | Path = "") -> None:
        main_repo = _get_main_repo()
        self.generated_tests_dir = (
            Path(generated_tests_dir)
            if generated_tests_dir
            else (main_repo / "tasks" / "nightly_agent" / "tests" / "generated")
        )
        self._main_repo = main_repo

    def validate(self, proposal: ArtifactProposal) -> TestResult:
        """
        1. 生成 test content
        2. 寫入 generated_tests_dir
        3. BEFORE：執行 test，必須 fail（artifact 尚未寫入）；若沒 fail 代表 friction 已修正
        4. 寫入 artifact（暫時性，僅用於驗證）
        5. AFTER：再執行 test，應該 pass
        6. 無論 AFTER 結果，rollback artifact（tester 只驗證；PRCreator 才是唯一寫入者）
        """
        generator = _TEST_GENERATORS.get(proposal.artifact_type)
        if generator is None:
            return TestResult(
                proposal_id=proposal.id,
                test_file="",
                passed=False,
                previously_failed=False,
                error=f"沒有 test generator for {proposal.artifact_type}",
            )

        test_content = generator(proposal)
        self.generated_tests_dir.mkdir(parents=True, exist_ok=True)

        safe_title = re.sub(r"[^a-z0-9_]", "_", proposal.title.lower())[:40]
        test_filename = f"test_nightly_{safe_title}_{proposal.id[:8]}.py"
        test_path = self.generated_tests_dir / test_filename

        test_path.write_text(test_content, encoding="utf-8")

        init_path = self.generated_tests_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text("", encoding="utf-8")

        # BEFORE: run test without artifact — must fail
        before_result = self._run_pytest(test_path)
        previously_failed = before_result.returncode != 0

        if not previously_failed:
            # Friction already fixed; do not open a PR
            return TestResult(
                proposal_id=proposal.id,
                test_file=str(test_path),
                passed=False,
                previously_failed=False,
                before_output=before_result.stdout[-500:] if before_result.stdout else "",
                after_output="",
                error="BEFORE test did not fail — friction may already be fixed; skipping PR",
            )

        # Write artifact (temporarily, for validation only)
        artifact_path = self._main_repo / proposal.target_file
        artifact_path.parent.mkdir(parents=True, exist_ok=True)

        original_content: str | None = None
        if artifact_path.exists():
            try:
                original_content = artifact_path.read_text(encoding="utf-8")
            except OSError:
                original_content = None

        self._apply_artifact(proposal, artifact_path)

        # AFTER: run test — expect pass
        after_result = self._run_pytest(test_path)
        passed = after_result.returncode == 0

        # Always rollback: tester validates only; PRCreator is the sole writer
        self._rollback_artifact(artifact_path, original_content)

        proposal.test_file = str(test_path)
        proposal.test_content = test_content

        return TestResult(
            proposal_id=proposal.id,
            test_file=str(test_path),
            passed=passed,
            previously_failed=previously_failed,
            before_output=before_result.stdout[-500:] if before_result.stdout else "",
            after_output=after_result.stdout[-500:] if after_result.stdout else "",
            error="" if passed else "Test failed after applying artifact",
        )

    def _run_pytest(self, test_path: Path) -> subprocess.CompletedProcess:  # type: ignore[type-arg]
        try:
            return subprocess.run(  # nosec B603 B607
                ["uv", "run", "pytest", str(test_path), "-x", "--tb=short", "-q"],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=str(self._main_repo),
            )
        except subprocess.TimeoutExpired:
            return subprocess.CompletedProcess(
                args=[], returncode=1, stdout="", stderr="pytest timed out after 60s"
            )

    def _apply_artifact(self, proposal: ArtifactProposal, artifact_path: Path) -> None:
        if proposal.artifact_type == ArtifactType.HOOKIFY_RULE:
            artifact_path.write_text(proposal.content, encoding="utf-8")
        elif proposal.artifact_type in (ArtifactType.CLAUDE_MD_GOTCHA, ArtifactType.SKILL_UPDATE):
            if artifact_path.exists():
                existing = artifact_path.read_text(encoding="utf-8")
                if not existing.endswith("\n"):
                    existing += "\n"
                artifact_path.write_text(
                    existing + "\n" + proposal.content + "\n", encoding="utf-8"
                )
            else:
                artifact_path.write_text(proposal.content + "\n", encoding="utf-8")

    def _rollback_artifact(self, artifact_path: Path, original: str | None) -> None:
        if original is None:
            try:
                artifact_path.unlink()
            except OSError as e:
                raise RuntimeError(
                    f"rollback 失敗（無法刪除暫存 artifact）：{artifact_path}"
                ) from e
        else:
            try:
                artifact_path.write_text(original, encoding="utf-8")
            except OSError as e:
                raise RuntimeError(f"rollback 失敗（無法還原原始內容）：{artifact_path}") from e
